services:
  sam3:
    build: .
    container_name: sam3-app
    restart: unless-stopped
    ports:
      - "7888:8888"
    volumes:
      - /opt/docker/roxan/data/sam3:/workspace/my_data
    environment:
      - HF_TOKEN=${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
